# use this however you see fit. feel free to optionally add either of the following comments to your file
#
# from github.com/sdolenc/bash-matrix/
# or
# inspired by github.com/sdolenc/bash-matrix/

version: 2.1
jobs:
  bash_5_0:
    docker:
      - image: bash:5.0
    <<: &commonSteps
      steps:
        - checkout
        - run:
            # bash 2.0 doesn't support set -o pipefail so we remove it by specifying the shell
            # this line can be removed if you're only testing bash 3.0 or above
            shell: /bin/sh -e

            command: |
              bash --version
  bash_4_4:
    docker:
      - image: bash:4.4
    <<: *commonSteps
  bash_4_3:
    docker:
      - image: bash:4.3
    <<: *commonSteps
  bash_4_2:
    docker:
      - image: bash:4.2
    <<: *commonSteps
  bash_4_1:
    docker:
      - image: bash:4.1
    <<: *commonSteps
  bash_4_0:
    docker:
      - image: bash:4.0
    <<: *commonSteps
  bash_3_2:
    docker:
      - image: bash:3.2
    <<: *commonSteps
  bash_3_1:
    docker:
      - image: bash:3.1
    <<: *commonSteps
  bash_3_0:
    docker:
      - image: bash:3.0
    <<: *commonSteps
  bash_2_05b:
    docker:
      - image: debian/eol:sarge
    <<: *commonSteps
  bash_2_05a:
    docker:
      - image: debian/eol:woody
    <<: *commonSteps
  bash_2_03:
    docker:
      - image: debian/eol:potato
    <<: *commonSteps
workflows:
  version: 2
  all:
    jobs:
      - bash_5_0
      - bash_4_4
      - bash_4_3
      - bash_4_2
      - bash_4_1
      - bash_4_0
      - bash_3_2
      - bash_3_1
      - bash_3_0
      - bash_2_05b
      - bash_2_05a
      - bash_2_03
