# use this however you see fit. feel free to optionally add either of the following comments to your file
#
# from github.com/sdolenc/bash-matrix/
# or
# inspired by github.com/sdolenc/bash-matrix/

name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - 5.0
        - 4.4
        - 4.3
        - 4.2
        - 4.1
        - 4.0
        - 3.2
        - 3.1
        - 3.0
    container: bash:${{ matrix.version }} 

    steps:
    - name: Clone Repo
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
        bash --version | head -2
        echo "test"
